### ISSUE TITLE
Missing (or omitted) `raspberrypi3-64` device type

### ISSUE THREAD

**Issue by xginn8** [balena-io-modules/balena-hup-action-utils#13]
Currently the RPi3 64-bit OS is marked as `BETA` and also not eligible for host OS upgrades in a confusing way. I will submit a PR to enable host OS upgrades, but feel free to reject & close if this is intentional. It's probably worth making the upgradability a bit clearer, however. (cc @imrehg)

**Comment by thgreasi** [comment]
@xginn8 is this still valid?

**Comment by imrehg** [comment]
IMHO closed by #14
